apiVersion: v1
kind: ConfigMap
metadata:
  name: policy
data:
  opa.rego: |
    package envoy.authz
    import input.attributes.request.http as http_request

    default allow = false

    allow {
        http_request.headers["endpoint"] == "/"
    }
