apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a # Name of the GSL file
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: ghcr.io/greymatter-io/example-deployments/hello-world-service-a:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Port that service-a listens on
          env:
            - name: SERVICE_PORT
              value: "8080"
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - port: 8080
      targetPort: 8080
