apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-flask-app
  labels:
    app: pg-flask-app
  annotations:
    greymatter.io/inject-sidecar-to: "5000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-flask-app
  template:
    metadata:
      labels:
        app: pg-flask-app
    spec:
      containers:
        - name: pg-flask-app
          image: ghcr.io/greymatter-io/example-deployments/pg-flask-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "pagila"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "yourpassword"
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
