apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  annotations:
    greymatter.io/inject-sidecar-to: "5432"
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-pagila
          image: busybox
          command: ["sh", "-c"]
          args:
            - wget -O /pagila/01-schema.sql https://raw.githubusercontent.com/devrimgunduz/pagila/master/pagila-schema.sql;
              wget -O /pagila/02-data.sql https://raw.githubusercontent.com/devrimgunduz/pagila/master/pagila-data.sql;
              sleep 10; # Sleep for a bit to ensure SQL files are fully downloaded
          volumeMounts:
            - name: pagila-sql
              mountPath: /pagila
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "pagila"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "yourpassword"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: pagila-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: pagila-sql
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
