apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b # Name of the GSL file
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: ghcr.io/greymatter-io/example-deployments/hello-world-service-b:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Port that service-a listens on
          env:
            - name: SERVICE_PORT
              value: "8080"
            - name: SERVICE_A_URL
              value: "http://localhost:10909/services/a"
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 10Mi
